[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  # Don't set publish directory for Next.js dynamic sites

[build.environment]
  # Ensure compatibility with Netlify Next.js plugin
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for API routes to work properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
